### ISSUE TITLE
视图选择。

### ISSUE THREAD

**Issue by xmfh** [PowerEasy/SmartGovManagement#1]
在`views`目录下的视图发生改变时，能够及时的重建缓存。 在后台的页面选择视图时，都能够看到实时的前台视图。

除了**推荐视图** 的目录， 其他的目录都应该是Ajax的请求。

**Comment by xmfh** [comment]
使用asp.net 依赖缓存技术
http://kb.cnblogs.com/page/69726/
例子中都是根据具体文件缓存的，我们最需要的应该是检测文件的添加和删除。

监控目录改变。
http://www.cnblogs.com/springyangwc/archive/2011/08/27/2155547.html
不知道在iis进程回收的时候会不会回收掉

http://stackoverflow.com/questions/541940/create-a-cache-dependancy-on-a-folder-and-its-sub-folder

1. 添加文件在N级子目录，是否会触发N次相关事件。
2. 通过文件管理器拷贝文件的话，是否会触发此事件。（如果触发，测试一下拷贝一个文件夹，文件夹里有4个文件，事件如何触发）
3. 修改目录名是触发change事件，还是触发add事件？

**Comment by xmfh** [comment]
多次触发事件 应该只能重建一次缓存。

> 可以注册`onchange`事件，每次onchange的时候，都将某个计时器重新计时， 当这个计时器能够最终运行的时候再进行缓存重建。

**Comment by jijinbi** [comment]
yes，sir

**Comment by xmfh** [comment]
经过讨论， 不需要再进行检测。  只清楚缓存，不再重建。

**Comment by jijinbi** [comment]
现在依赖缓存暂时存在的bug就是文件监控的多次触发，导致会多次判断是否要清楚缓存
